export default [
  {
    year: "1977",
    title: "Talking Heads 77",
    wordCount: "2799",
    backgroundColor: "#c22c20",
    textColor: "#000000",
    words: [
      "na na na",
      "fa fa fa",
      "can’t",
      "week",
      "i’m",
      "talk",
      "day",
      "happy",
      "yeah",
      "feel",
      "concerned",
      "pulled",
      "want",
      "gonna",
      "read",
      "confuse",
      "problems",
      "worry",
      "love",
      "decide",
      "building",
      "run",
    ],
  },
  {
    year: "1978",
    title: "More Songs About Buildings and Food",
    wordCount: "2799",
    backgroundColor: "#b4373b",
    textColor: "#000000",
    words: [
      "love",
      "girl",
      "trou",
      "boys",
      "reme",
      "look",
      "peop",
      "baby",
      "see",
      "want",
      "time",
      "like",
      "hung",
      "got",
      "thin",
      "make",
      "wate",
      "sign",
      "mean",
      "stay",
      "warn",
      "take",
    ],
  },
  {
    year: "1979",
    title: "Fear of Music",
    wordCount: "1945",
    backgroundColor: "#1b1517",
    textColor: "#81d774",
    words: [
      "never",
      "paper",
      "ain’t",
      "party",
      "everyone",
      "home",
      "make",
      "think",
      "need",
      "i’m",
      "stay",
      "electric",
      "charged",
      "they’re",
      "remember",
      "heaven",
      "people",
      "baby",
      "know",
      "rays",
      "nothing",
      "like",
    ],
  },
  {
    year: "1980",
    title: "Remain in Light",
    wordCount: "2613",
    backgroundColor: "#63a8d9",
    textColor: "#000000",
    words: [
      "water",
      "i’m",
      "goes",
      "heat",
      "world",
      "darker",
      "wind",
      "need",
      "move",
      "underground",
      "heart",
      "still",
      "waiting",
      "ever",
      "facts",
      "days",
      "mojique",
      "define",
      "flowing",
      "hold",
      "hands",
      "letting",
    ],
  },
  {
    year: "1983",
    title: "Speaking in Tongues",
    wordCount: "2493",
    backgroundColor: "#eab400",
    textColor: "#000000",
    words: [
      "mind",
      "get",
      "pull",
      "know",
      "time",
      "roots",
      "right",
      "nothing",
      "gonna",
      "need",
      "got",
      "go",
      "girlfriend",
      "wheel",
      "home",
      "wild",
      "house",
      "moon",
      "i’ll",
      "eyes",
      "i’m",
      "better",
    ],
  },
  {
    year: "1985",
    title: "Little Creatures",
    wordCount: "2163",
    backgroundColor: "#91f087",
    textColor: "#000000",
    words: [
      "creatures",
      "know",
      "baby",
      "nowhere",
      "love",
      "take",
      "alright",
      "we’re",
      "man",
      "little",
      "television",
      "world",
      "night",
      "long",
      "come",
      "make",
      "somebody",
      "like",
      "i’m",
      "walk",
      "sympathy",
      "things",
    ],
  },
  {
    year: "1986",
    title: "True Stories",
    wordCount: "2063",
    backgroundColor: "#ed1222",
    textColor: "#ffffff",
    words: [
      "hey",
      "wild",
      "love",
      "puzzling",
      "dream",
      "people",
      "huh",
      "oh",
      "like",
      "evidence",
      "got",
      "radio",
      "life",
      "gonna",
      "come",
      "night",
      "children",
      "rompiendo",
      "puzzling",
      "head",
      "heart",
      "world",
    ],
  },
  {
    year: "1988",
    title: "Naked",
    wordCount: "2736",
    backgroundColor: "#b6613a",
    textColor: "#000000",
    words: [
      "blind",
      "got",
      "like",
      "he’s",
      "jones",
      "daddy",
      "i’m",
      "little",
      "one",
      "work",
      "life",
      "like",
      "big",
      "driving",
      "rain",
      "oh",
      "huh",
      "coming",
      "uh",
      "love",
      "mr.",
      "facts",
    ],
  },
  {
    year: "1989",
    title: "Rei Momo",
    wordCount: "3335",
    backgroundColor: "#fbdc29",
    textColor: "#000000",
    words: [
      "want",
      "time",
      "long",
      "world",
      "i’m",
      "waiting",
      "know",
      "independence",
      "mundo",
      "oh",
      "like",
      "day",
      "wrong",
      "good",
      "rosa",
      "people",
      "que",
      "night",
      "men",
      "turned",
      "evil",
      "dream",
    ],
  },
  {
    year: "1992",
    title: "Uh Oh",
    wordCount: "3221",
    backgroundColor: "#e3c2de",
    textColor: "#000000",
    words: [
      "hey",
      "nuh",
      "look",
      "tiny",
      "oh",
      "ain’t",
      "somebody",
      "town",
      "mind",
      "gonna",
      "i’m",
      "well",
      "got",
      "know",
      "girls",
      "around",
      "dark",
      "hangin’",
      "little",
      "right",
      "something",
      "ooh",
    ],
  },
  {
    year: "1994",
    title: "David Byrne",
    wordCount: "2571",
    backgroundColor: "#65695a",
    textColor: "#000000",
    words: [
      "i’m",
      "love",
      "naked",
      "we’re",
      "long",
      "like",
      "box",
      "back",
      "strange",
      "nothing",
      "lost",
      "way",
      "ready",
      "got",
      "ritual",
      "saw",
      "well",
      "see",
      "keep",
      "buck",
      "supposed",
      "shines",
    ],
  },
  {
    year: "1997",
    title: "Feelings",
    wordCount: "2944",
    backgroundColor: "#3d80ab",
    textColor: "#000000",
    words: [
      "love",
      "i’m",
      "daddy",
      "holiday",
      "away",
      "wicked",
      "go",
      "little",
      "everyone’s",
      "doll",
      "time",
      "burnt",
      "sun",
      "like",
      "war",
      "miles",
      "taking",
      "america",
      "music",
      "much",
      "clouds",
      "dance",
    ],
  },
  {
    year: "2001",
    title: "Look into the Eyeball",
    wordCount: "2631",
    backgroundColor: "#fcd66b",
    textColor: "#000000",
    words: [
      "i’m",
      "things",
      "soy",
      "like",
      "love",
      "smile",
      "neighborhood",
      "breathin",
      "jesus",
      "house",
      "see",
      "kiss",
      "everyone",
      "humans",
      "broken",
      "walk",
      "funky",
      "sister",
      "could",
      "el",
      "drive",
      "help",
    ],
  },
  // {
  //   year: "2004",
  //   title: "Grown Backwards",
  //   wordCount: "2631",
  //   backgroundColor: "#e2e3dd",
  //   textColor: "#000000",
  //   words: [
  //     "i’m",
  //     "lazy",
  //     "glad",
  //     "know",
  //     "pirates",
  //     "got",
  //     "imagine",
  //     "like",
  //     "wicked",
  //     "man",
  //     "gonna",
  //     "parade",
  //     "home",
  //     "there’s",
  //     "sleeps",
  //     "life",
  //     "night",
  //     "today",
  //     "side",
  //     "sleeps",
  //     "eyes",
  //     "things",
  //   ],
  // },
  // {
  //   year: "2008",
  //   title: "Everything That Happens Will Happen Today",
  //   wordCount: "2631",
  //   backgroundColor: "#82bb40",
  //   textColor: "#000000",
  //   words: [
  //     "home",
  //     "i’m",
  //     "life",
  //     "eyes",
  //     "one",
  //     "soul",
  //     "away",
  //     "words",
  //     "never",
  //     "thought",
  //     "river",
  //     "ev’ry",
  //     "standing",
  //     "poor",
  //     "little",
  //     "river",
  //     "still",
  //     "see",
  //     "stuff",
  //     "long",
  //     "oh",
  //     "gonna",
  //   ],
  // },
  // {
  //   year: "2018",
  //   title: "American Utopia",
  //   wordCount: "2018",
  //   backgroundColor: "#a8aeb3",
  //   textColor: "#000000",
  //   words: [
  //     "i’m",
  //     "house",
  //     "that’s",
  //     "thing",
  //     "day",
  //     "like",
  //     "right",
  //     "hey",
  //     "bullet",
  //     "never",
  //     "everybody",
  //     "coming",
  //     "gonna",
  //     "there’s",
  //     "nothing",
  //     "dance",
  //     "always",
  //     "home",
  //     "went",
  //     "every",
  //     "got",
  //     "another",
  //   ],
  // },
]
