export default [
  {
    year: "1977",
    title: "Talking Heads 77",
    wordCount: "2799",
    backgroundColor: "#c22c20",
    textColor: "#000000",
    words: [
      "na na na",
      "fa fa fa",
      "can’t",
      "week",
      "i’m",
      "talk",
      "day",
      "happy",
      "yeah",
      "feel",
      "concerned",
      "pulled",
      "want",
      "gonna",
      "read",
      "confuse",
      "problems",
      "worry",
      "love",
      "decide",
      "building",
      "run",
    ],
  },
]
